[package]
name = "litris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lighthouse-client = { version = "0.4", features = ["tokio"] }
tokio = { version = "1.21", features = ["rt", "macros"] }
futures = "0.3"
tracing = "0.1"
rand = "0.8"
tracing-subscriber = { version = "0.3", features = ["env-filter", "std"] }
